### ISSUE TITLE
On the simple ring theorem

### ISSUE THREAD

**Issue by R1mo17** [ZhY-Zhang/RMT-DEPRECATED-#1]
您好：
        我看关于单环定理应用的文献里，获取X的奇异等价矩阵采用的方法与您算法里的不太一致。是不是等效的。
如果可以的话能跟您邮件沟通吗。谢谢
[Detection_and_Localization_of_Submodule_Open-Circuit_Failures_for_Modular_Multilevel_Converters_With_Single_Ring_Theorem.pdf](https://github.com/ZhY-Zhang/RMT/files/10546264/Detection_and_Localization_of_Submodule_Open-Circuit_Failures_for_Modular_Multilevel_Converters_With_Single_Ring_Theorem.pdf)

**Comment by ZhY-Zhang** [comment]
您好：
这个项目是我做大作业的半成品，现已废弃。里面获取 singular value equivalent matrix 的代码的确有误。我后续有重新推导过相关公式，如您有需要我们可以继续在邮件上沟通。但本人水平有限，推导内容不保证可靠。

**Comment by R1mo17** [comment]
十分感谢您的解答，关于单环定理的算法更新了吗，我能看一下您的推导内容吗。



在 2023-02-01 10:58:09，"Zhang Zhuangyan" ***@***.***> 写道：

您好：
这个项目是我做大作业的半成品，现已废弃。里面获取 singular value equivalent matrix 的代码的确有误。我后续有重新推导过相关公式，如您有需要我们可以继续在邮件上沟通。但本人水平有限，推导内容不保证可靠。

**Comment by ZhY-Zhang** [comment]
我把推导放在readme文件里面了，不过github不支持latex公式，你可以下载或复制后用别的软件或网页打开。本项目已经弃用，代码没有改也不会再改了。
